config/routes.rb
KorpslimmatCh::Application.routes.draw do
  
  namespace :event do
    resources :signups
  end

  resources :people

  resources :groups

  devise_for :users
  get "index/index"
  get "index/about"

  scope 'events' do
    get ':id' => 'events#show', as: :event
    post 'signup' => 'events#signup'
  end

  root "index#index"

  

end

app/models/event.rb
module Event
  def self.table_name_prefix
    'event_'
  end
end

app/models/event/signup.rb
class Event::Signup < ActiveRecord::Base
  require 'yaml'
  belongs_to :event

  def signup_options=o
    self.options_serialized = YAML::dump(o)
  end

  def signup_options
    YAML::load(options_serialized) rescue nil
  end

  validates :name, presence: true

end

app/models/group.rb
class Group < ActiveRecord::Base

  belongs_to :parent, class_name: 'Group'
  has_many :people_functions, class_name: 'GroupFunction'
  has_many :people, through: :people_functions


  def to_s
    name
  end
end

app/models/group_function.rb
class GroupFunction < ActiveRecord::Base
  belongs_to :group
  belongs_to :person
end

app/models/mail_alias.rb
class MailAlias < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base

  has_many :group_functions
  has_many :groups, through: :group_functions
  has_one  :user
  #has_many :mail_aliases, polymorphic: true

end

app/models/role.rb
module Role
  ROLES = %i(user admin)

  extend ActiveSupport::Concern

  included do
    def roles=(roles)
      self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
    end

    def roles
      ROLES.reject do |r|
        ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
      end
    end

    def has_role role
      roles.include?(role.to_sym)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable

  include Role

  belongs_to :person

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :view_options
  def view_options options={}
    @view_options ||= {
        single_page: false,
    }
    @view_options.merge! options
  end
end

app/controllers/event/signups_controller.rb
class Event::SignupsController < ApplicationController
  before_action :set_event_signup, only: [:show, :edit, :update, :destroy]
  require 'csv'

  # GET /event/signups
  def index
    @event_signups = Event::Signup.all

    respond_to do |format|
      format.csv do
        csv = CSV.generate force_quotes: true do |rows|

          # data rows
          @event_signups.each do |signup|
            rows << [signup.name] + signup.signup_options.map { |k, v| "#{k}: #{v}" }
          end
        end

        send_data(csv, type: 'text/csv', filename: 'signups.csv')
      end
    end
  end

  # GET /event/signups/1
  def show
  end

  def new
    @event_signup = Event::Signup.new
  end

  def edit
  end

  def create
    @event_signup = Event::Signup.new(event_signup_params)

    if @event_signup.save
      Rails.logger.debug @event_signup.inspect
      redirect_to event_path(:diff14), notice: 'Danke für deine Anmeldung.'
    else
      render 'events/static/diff14'
    end
  end

  # PATCH/PUT /event/signups/1
  def update
    if @event_signup.update(event_signup_params)
      redirect_to @event_signup, notice: 'Signup was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /event/signups/1
  def destroy
    @event_signup.destroy
    redirect_to event_signups_url, notice: 'Signup was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_signup
      @event_signup = Event::Signup.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def event_signup_params
      params.require(:event_signup).permit!
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
  end

  def show
    @event = params[:id]
    @event_signup = Event::Signup.new

    return unless ['diff14'].include?(@event)

    render "events/static/#{@event}"
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  def index
    @groups = Group.all
  end

  # GET /groups/1
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to @group, notice: 'Group was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /groups/1
  def update
    if @group.update(group_params)
      redirect_to @group, notice: 'Group was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /groups/1
  def destroy
    @group.destroy
    redirect_to groups_url, notice: 'Group was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def group_params
      params.require(:group).permit(:name, :parent_id)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    view_options single_page: true
  end

  def about
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  def index
    @people = Person.all
  end

  # GET /people/1
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to @person, notice: 'Person was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /people/1
  def update
    if @person.update(person_params)
      redirect_to @person, notice: 'Person was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /people/1
  def destroy
    @person.destroy
    redirect_to people_url, notice: 'Person was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :vulgo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event/signups_helper.rb
module Event::SignupsHelper
end

app/helpers/form_helper.rb
module FormHelper
end

app/helpers/show_helper.rb
module ShowHelper

  def button_show path, size="xs", style=""
    link_to path, class: "btn btn-#{size} #{style}" do
      tag :i, class: 'fa fa-eye'
    end
  end

  def button_edit path, size="xs", style=""
    link_to path, class: "btn btn-#{size} #{style}" do
      tag :i, class: 'fa fa-pencil'
    end
  end

  def button_destroy path, size="xs", style="btn-danger"
    link_to path, class: "btn btn-#{size} #{style}", method: :delete, data: { confirm: 'Are you sure?' } do
      tag :i, class: 'fa fa-trash-o'
    end
  end

end

app/views/groups/_form.html.haml
= simple_form_for(@group, html: { class: "form-horizontal", role: "form" }) do |f|
  = f.input :name
  = f.association :parent
  = f.button :submit

app/views/groups/edit.html.haml
%h1 Editing group

= render 'form'

= link_to 'Show', @group
\|
= link_to 'Back', groups_path

app/views/groups/index.html.haml
= render layout: 'layouts/nested/default' do
  %h1 Neue Gruppe

  %table.table
    %thead
      %tr
        %th Name
        %th Parent
        %th.actions= link_to 'Neue Gruppe', new_group_path, class: 'btn btn-default btn-xs'

    %tbody
    - @groups.each do |group|
      %tr
        %td= group.name
        %td= link_to_if group.parent.present?, group.parent
        %td.actions
          = button_show group_path(group)
          = button_edit edit_group_path(group)
          = button_destroy group_path(group)

app/views/groups/new.html.haml
= render layout: 'layouts/nested/default' do

  %h1 Neue Gruppe

  = render 'form'

app/views/groups/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @group.name
%p
  %b Parent:
  = @group.parent

= link_to 'Edit', edit_group_path(@group)
\|
= link_to 'Back', groups_path

app/views/index/about.html.haml
%section#about
  .container
    .row.prallax
      .col-md-4
        = image_tag "layouts/badge.png"
      .col-md-8
        %h3 Der Korps Limmat stellt sich vor
        %p
          Gestatten? Wir sind der Pfadikorps Limmat aus Zürich. Der Korps ist ein Zusammenschluss verschiedenster Pfadiabteilungen
          rund um die Limmat.
        %br/
        %p
          Auch wenn wir nicht direkt selbst jeden Samstag tolle Aktivitäten in Stadt, Wald und Wiese veranstalten, tragen wir
          doch einen guten Teil dazu bei, dass Kinder und Jugendliche jede Woche Pfadi erleben dürfen. Unsere Ziele sind,
          Synergien zu Nutzen, die Abteilungen mit der schweizweiten Pfadibewegung zu koordinieren und Ausbildungskurse zu
          veranstalten.
        %br/
        %p
          Wir freuen uns, für dich, deine Leiter und deine Abteilung da zu sein!

app/views/index/current.html.haml
%section#current
  .container
    -#.container-background= image_tag "news/feed.svg"
    .row
      .col-md-7
        %h3 News
        %ul#news
          %li
            %h4
              DiFF 14
              %small.issuer Korpsleitung
              %small.issued_at
                %i.fa.fa-clock-o
                = l(DateTime.new(2014, 4, 2, 20), format: :short)
            %p.content
              Der Korps Limmat veranstaltet das diesjährige DiFF. Endlich ist nun auch der
              = link_to("Flyer und die Anmeldung", event_path(:diff14))
              online!
          %li
            %h4
              Webseite
              %small.issuer Korpsleitung
              %small.issued_at
                %i.fa.fa-clock-o
                = l(DateTime.new(2014, 2, 1, 20), format: :short)
            %p.content
              Das sind immer die ersten News: Unsere neue Webseite ist online! Sieht schon mal prächtig aus, bietet aber noch lange nicht das an,
              was sie eigentlich könnte. Wir werden weiterhin daran Arbeiten und halten euch auf dem Laufenden!
      .col-md-4.col-md-push-1
        %h3 Agenda
        %ul#events
          %li#template_event.event
            %h4.what
            .when
              %i.fa.fa-calendar-o
              %span
            .who
              %i.fa.fa-group
              %span
            .where
              %i.fa.fa-map-marker
              %span
            .description
              %i.fa.fa-envelope
              %a.more mehr zu diesem Event
              %p

app/views/index/index.html.haml
= render file: "index/about"

= render file: "index/team"

= render file: "index/current"

app/views/index/team.html.haml
%section#team
  .container
    .row
      .col-md-12
        %h3 Team
    .row
      .col-md-3
        .member-picture{ style: "background-image: url(#{image_path "team/filou.JPG"});" }
      .col-md-3
        .member-description
          %h4 Filou
          .name  Diego Steiner v/o Filou
          .function Korpsleiter
          .description
      .col-md-3
        .member-picture{ style: "background-image: url(#{image_path "team/saida.JPG"}); " }
      .col-md-3
        .member-description
          %h4 Saïda
          .name  Sarah Münst v/o Saïda
          .function Korpsleiterin
          .description
    .row
      .col-md-3
        .member-picture{ style: "background-image: url(http://on-board.co.uk/wp-content/uploads/2013/09/OB-missing-male.jpg);" }
      .col-md-3
        .member-description
          %h4 Spatz
          .name Patrick Müller v/o Spatz
          .function Ressort Administration
          .description
      .col-md-3
        .member-picture{ style: "background-image: url(#{image_path "team/frosch.JPG"});" }
      .col-md-3
        .member-description
          %h4 Frosch
          .name Daniel Jecklin v/o Frosch
          .function Piostufen Verantwortlicher
          .description
    .row
      .col-md-12
        %h3 Abteilungen
      .col-md-3
        %h4
          Säuliamt
          %small Affoltern am Albis
        %a.abteilungs-picture{ href: "http://pfadi-sa.ch", style: "background-image: url(http://www.mettmenstetten.ch/de/images/519dc0a093adb.jpg);" }
      .col-md-3
        %h4
          Sempach
          %small Zürich-Altstetten
        %a.abteilungs-picture{ href: "http://pfadisempach.ch", style: "background-image: url(http://pfadisempach.ch/Bilder/logo.gif);" }
      .col-md-3
        %h4
          Laupen
          %small Engstringen
        %a.abteilungs-picture{ href: "http://pfadilaupen.ch", style: "background-image: url(http://www.oberengstringen.ch/de/images/40a864d4697b9.jpg);" }
      .col-md-3
        %h4
          St. Mauritius Nansen
          %small Zürich-Höngg
        %a.abteilungs-picture{ href:  "http://pfadismn.ch", style: "background-image: url(http://pfadismn.ch/pfadismn.svg);" }
      .col-md-3
        %h4
          St. Ulrich
          %small Dietikon
        %a.abteilungs-picture{ href:  "http://pfadi-stulrich.ch", style: "background-image: url(http://www.pfadi-stulrich.ch/wordpress/wp-content/uploads/2011/02/PSU.jpg);" }
      .col-md-3
        %h4
          Uro
          %small Urdorf
        %a.abteilungs-picture{ href:  "http://pfadiuro.ch", style: "background-image: url(http://u.jimdo.com/www61/o/s64b4607fa1807dd4/img/id3082adcbba1d1c5/1363531101/std/image.gif);" }
      .col-md-3
        %h4
          Morgarten-Erlach
          %small Zürich-Wipkingen
        .abteilungs-picture
          %a{ href: "http://pfadimoe.ch" }
      .col-md-3
        %h4
          Murten
          %small Zürich-Altstetten
        %a.abteilungs-picture{ href:  "http://pfadi-murten.ch", style: "background-image: url(http://pfadismn.ch/pfadismn.svg);" }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Pfadikorps Limmat'
    %meta{name: "description", content: "#{content_for?(:description) ? yield(:description) : 'Pfadiheime'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body{ class: "#{controller_name}_controller #{action_name}_action #{ view_options[:single_page] ? 'single_page' : ''}" }
    = render 'layouts/shared/header'
    = render 'layouts/shared/effects'
    %main{ role: 'main'}
      = render 'layouts/shared/alerts'
      = yield
    = render 'layouts/shared/footer'

app/views/layouts/nested/_default.html.haml
.container
  .row
    .col-md-12
      = yield

app/views/layouts/shared/_alerts.html.haml
-# Rails flash messages styled for Twitter Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    .container
      .row
        .col-md-12
          %div{class: "alert alert-#{name == :notice ? "success" : "danger"}"}
            %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} &times;
            = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/shared/_effects.html.haml
#lilie-big
#scroll-down
  %i.fa.fa-chevron-down.fa-2x

app/views/layouts/shared/_footer.html.haml
%footer
  .container
    .row
      .col-md-3.footer
        %h3 Kontakt
        %address
          Diego Steiner v/o Filou
          %br
          Bachmannweg 7
          %br
          8046 Zürich
          %br
          = mail_to "info@korpslimmat.ch"

      .col-md-3.footer
        %h3 Impressum
        &copy; 2014 Korps Limmat
      .col-md-3.footer
        %h3 Links
        %ul
          %li= link_to "Pfadi Züri", "http://www.pfadizueri.ch"
          %li= link_to "Distrikt St. Georg", "http://www.distrikt.ch"
          %li= link_to "Pfadiheime", "http://www.pfadiheime.ch"
      .col-md-3.footer
        .pfadizueri
          = link_to "http://www.pfadizueri.ch/" do
            = image_tag "http://www.pfadizueri.ch/tl_files/design/plogo.png"

app/views/layouts/shared/_header.html.haml
%header
  #brand-outer
    #brand-inner
      .container
        .row
          .col-md-12
            #logo
              = link_to root_path do
                = image_tag 'layouts/badge.png'
            #title
              %h1 Korps Limmat
              %h2.scrollpos Die Pfadiabteilungen aus der Region Limmat

  #nav
    .container
      .row
        .col-md-12
          = render 'layouts/shared/navigation'
  #header-fader

app/views/layouts/shared/_navigation.html.haml
%nav
  %ul
    %li
      %a{ href: "#about"} Über uns
    %li
      %a{ href: "#current"} Aktuell
    %li
      %a{ href: "#downloads"} Downloads
    %li
      %a{ href: "#contact"} Kontakt

app/views/people/_form.html.haml
= form_for @person do |f|
  - if @person.errors.any?
    #error_explanation
      %h2= "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
      %ul
        - @person.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :vulgo
    = f.text_field :vulgo
  .actions
    = f.submit 'Save'

app/views/people/edit.html.haml
%h1 Editing person

= render 'form'

= link_to 'Show', @person
\|
= link_to 'Back', people_path

app/views/people/index.html.haml
%h1 Listing people

%table
  %tr
    %th First name
    %th Last name
    %th Vulgo
    %th
    %th
    %th

  - @people.each do |person|
    %tr
      %td= person.first_name
      %td= person.last_name
      %td= person.vulgo
      %td= link_to 'Show', person
      %td= link_to 'Edit', edit_person_path(person)
      %td= link_to 'Destroy', person, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Person', new_person_path

app/views/people/new.html.haml
%h1 New person

= render 'form'

= link_to 'Back', people_path

app/views/people/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @person.first_name
%p
  %b Last name:
  = @person.last_name
%p
  %b Vulgo:
  = @person.vulgo

= link_to 'Edit', edit_person_path(@person)
\|
= link_to 'Back', people_path